apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: OpenSearch
    type: opensearch
    access: proxy
    url: http://opensearch:9200
    database: "fluentbit-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "2.11.0"
      logMessageField: log
      logLevelField: level
