version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cloudscale
      POSTGRES_USER: cloudscale_admin
      POSTGRES_PASSWORD: localdev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudscale_admin -d cloudscale"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.auth-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudscale
      DB_USER: cloudscale_admin
      DB_PASSWORD: localdev123
      JWT_SECRET: local-dev-secret
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.order-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudscale
      DB_USER: cloudscale_admin
      DB_PASSWORD: localdev123
      JWT_SECRET: local-dev-secret
    depends_on:
      postgres:
        condition: service_healthy

  payment-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.payment-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudscale
      DB_USER: cloudscale_admin
      DB_PASSWORD: localdev123
      JWT_SECRET: local-dev-secret
    depends_on:
      postgres:
        condition: service_healthy

  analytics-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.analytics-service
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudscale
      DB_USER: cloudscale_admin
      DB_PASSWORD: localdev123
      JWT_SECRET: local-dev-secret
      AWS_REGION: us-east-1
      KINESIS_STREAM_NAME: cloudscale-events-production
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
