apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cloudscale
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: payment-service
      containers:
        - name: payment-service
          image: cloudscale/payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
              protocol: TCP
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secrets
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
